### ISSUE TITLE
BACK_300 Servidor de hospedaje

### ISSUE THREAD

**Issue by JoelSolano59** [31-Horas/server#1]
Negocio: Como usuario, podré acceder a la plataforma y a la información almacenada en ella en cualquier momento y lugar, gracias al servidor de hospedaje.

Técnico: Se seleccionará y configurará un servidor externo que permita alojar tanto la base de datos como la página web.
Se garantizará que el servidor esté disponible las 24 horas del día, los 365 días del año.
Se asegurará que la base de datos y la página web estén correctamente configuradas y funcionando en el servidor de hospedaje.

Story Points:
1

Criterios de aceptación:

El servidor de hospedaje estará disponible las 24 horas del día, los 365 días del año.
La base de datos y la página web estarán alojadas y funcionando correctamente en el servidor de hospedaje.

**Comment by RodoBP** [comment]
Servido generado en AWS
